- hosts: all
  gather_facts: yes
  become: yes
  roles:
#    - { role: debug, tags: debug}
    - { role: common}

- hosts: hetznerserver, hetznercloud
  gather_facts: yes
  become: yes
  roles:
    - { role: hetzner, tags: hetzner}
    - { role: centos-plus, tags: centosplus}

- hosts: hetznerserver, localhost
  gather_facts: yes
  become: yes
  roles:
    - { role: thinpool, tags: thinpool}

- hosts: lxc
  gather_facts: yes
  become: yes
  roles:
    - { role: lxc, tags: lxc}

- hosts: gan
  gather_facts: yes
  become: yes
  roles:
    - { role: gan, tags: gan}

- hosts: docker
  gather_facts: yes
  become: yes
  roles:
    - { role: docker, tags: docker}

- hosts: gluster
  gather_facts: yes
  become: yes
  roles:
    - { role: gluster, tags: gluster }

- hosts: x2go
  gather_facts: yes
  become: yes
  roles:
    - { role: x2go, tags: x2go}

- hosts: libvirt
  gather_facts: yes
  become: yes
  roles:
    - { role: libvirt, tags: libvirt}

- hosts: vm
  gather_facts: yes
  become: yes
  roles:
    - { role: vm, tags: vm}

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }

- hosts: node
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }

- hosts: workstation
  gather_facts: yes
  become: yes
  roles:
#    - { role: common}
#    - { role: thinpool}
#    - { role: docker, tags: docker}
#    - { role: libvirt, tags: libvirt}
    - { role: workstation, tags: workstation }
