---

#- name: Reset Kubernetes component
#  shell: "kubeadm reset --force"
#  register: reset_cluster
#
#- name: Join to Kubernetes cluster
#  when: reset_cluster is succeeded
#  shell: |
#    kubeadm join --token {{ token }} \
#                --discovery-token-unsafe-skip-ca-verification \
#                {{ master_ip }}:6443
#  register: join_cluster
#  notify:
#    - Recreate kube-dns

- name: create .kube directory
  become: yes
  become_user: "{{ admin }}"
  file:
    path: "/home/{{ admin }}/.kube"
    state: directory
    mode: 0755

- name:  Kube Config
  copy:
    src: roles/kubernetes/master/files/admin.conf
    dest: "/home/{{ admin }}/.kube/config"
    
- name: Copy Join Command
  become: yes
  become_user: "{{ admin }}"
  copy:
    src: roles/kubernetes/master/files/kube_join.sh
    dest: "/home/{{ admin }}/kube_join.sh"

- name: Join Cluster
  shell: "sh /home/{{ admin }}/kube_join.sh"